config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'api/users', controllers: {
    registrations: "api/users",
    sessions: "api/sessions"} do
    get "login", to: "sessions#new"
  end
  get "/", to: "static_pages#root", constraints: { subdomain: "download" }
  get "admin", to: "static_pages#admin"
  devise_scope :user do
    get "login", to: "api/sessions#new"
  end


  namespace :api, defaults: {format: :json} do
    resources :patterns, only: [:show, :destroy, :index]
    resources :pattern_files, only: [:create, :show, :update, :destroy, :index]
    resources :download_codes, only: [:create, :show, :update, :destroy, :index] do
      get 'search', on: :collection
    end
    resources :etsy_patterns, only: [:create, :update]
    resources :indie_patterns, only: [:create, :update]
  end

  root "static_pages#root"
end

app/models/pattern_file.rb
class PatternFile < ActiveRecord::Base
  validates :name, :pattern, :filepicker_url, :filename, presence: true

  has_attached_file :content
  belongs_to :pattern
end

app/controllers/api/pattern_files_controller.rb
class Api::PatternFilesController < ApplicationController
  before_action :require_admin

  def create
    @pattern_file = PatternFile.new(pattern_file_params)
    if @pattern_file.save
      render json: @pattern_file
    else
      render json: @pattern_file.errors.full_message, status: 422
    end
  end

  def show
    @pattern_file = PatternFile.new
    render json: @pattern_file
  end

  private
  def pattern_file_params
    params.require(:pattern_file).permit(:pattern_id, :filepicker_url, 
                                         :filename, :name)
  end
end

app/views/pattern_files/_form.html.erb
<!-- <form action="<%= pattern_files_url %>" method="post" enctype="multipart/form&#45;data"> -->
<!--   <%= auth_token %> -->
<!--   <input type="hidden" name="pattern_file[pattern_id]" value="<%= pattern.id %>"/> -->
<!--   <label for="pattern_file_name">File Name</label> -->
<!--   <input type="text" name="pattern_file[name]" id="pattern_file_name"/> -->
<!--   <input type="file" name="pattern_file[content]"/> -->
<!--   <input type="submit" value="Upload" /> -->
<!-- </form> -->


<%= form_for @pattern_file do |f| %>
  <div>
    <%= hidden_field(:pattern_file, :pattern_id, value: pattern.id) %>
    <%= f.label :name, "File name:" %>
    <%= f.text_field :name %>
    <%= f.label :filepicker_url, "Choose a file:" %>
    <%= f.filepicker_field :filepicker_url, onchange: 'onPhotoUpload(event)' %> <!-- User#filepicker_url is a regular string column -->
  </div>

  <%= f.submit %>
<% end %>

app/views/pattern_files/_pattern_file.html.erb
<h4><%= pattern_file.name %> <%= pattern_file.content.url %></h4>